global:
  scrape_interval: 15s # Thu thap du lieu trong 15s

scrape_configs:
  - job_name: "tetticket-prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["prometheus:9090"]
    metrics_path: "/metrics"

  - job_name: "tetticket-springboot"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:1122"]
    metrics_path: "/actuator/prometheus"

  - job_name: "tetticket-node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "tetticket-mysql-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["myslq-exporter:9104"]
    metrics_path: "/metrics"